### ISSUE TITLE
Color de texto

### ISSUE THREAD

**Issue by raquelvilla** [miauhaus/miauhaus.github.io#87]
![chrome_2019-03-30_11-44-13](https://user-images.githubusercontent.com/44376440/55275126-cd7ab100-52e1-11e9-9cee-e6bee37bad18.png)

Si hay acuerdo general, subir el brillo del texto. A color blanco. La referencia es de https://designawards.core77.com/
que la acabo de encontrar aleatoriamente

**Comment by miauhaus** [comment]
ok

**Comment by miauhaus** [comment]
lo he cambiado, a mi me gusta mas en el color de antes

**Comment by raquelvilla** [comment]
si? A mí este, lo podemos ver con el resto
